name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v6

      - name: 🦆 Install pnpm
        uses: pnpm/action-setup@v5

      - name: 🛠️ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 📦 Install deps
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 🗂️ Setup turbo cache
        uses: rharkor/caching-for-turbo@v1.8

      - name: 🏷️ Typecheck
        run: pnpm typecheck

      - name: 🔬 Lint
        run: pnpm lint

      - name: 🧪 Test
        run: pnpm test

      - name: 👷 Build
        run: pnpm turbo build
