name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🛠️ Setup environment
        uses: ./.github/actions/setup-env

      - name: 🏷️ Typecheck
        run: pnpm typecheck

      - name: 🔬 Lint
        run: pnpm lint

      - name: 🧪 Test
        run: pnpm test

      - name: 👷 Build
        run: pnpm turbo build
