name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🦆 Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0

      - name: 🛠️ Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 📦 Install deps
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 🗂️ Setup turbo cache
        uses: rharkor/caching-for-turbo@0abc2381e688c4d2832f0665a68a01c6e82f0d6c # v2.3.11

      - name: 🏷️ Typecheck
        run: pnpm typecheck

      - name: 🔬 Lint
        run: pnpm lint

      - name: 🧪 Test
        run: pnpm test

      - name: 👷 Build
        run: pnpm turbo build
